### ISSUE TITLE
Standing orders endpoint is not working

### ISSUE THREAD

**Issue by dcguim** [femueller/python-n26#113]
I believe the standing orders endpoint is not working, follow the result of`api_client.get_standing_orders()`:
```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    print(api_client.get_standing_orders())
  File ".../python-n26/n26/api.py", line 184, in get_standing_orders
    return self._do_request(GET, BASE_URL_DE + '/api/transactions/so')
  File ".../python-n26/n26/api.py", line 310, in _do_request
    response.raise_for_status()
  File ".../venv/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.tech26.de/api/transactions/so
```

**Comment by femueller** [comment]
@dcguim Haven't checked that specific endpoint recently, but it could be that N26 deprecated it.

**Comment by markusressel** [comment]
We probably have to get the new API working, which has been discussed a lot in #110.
