### ISSUE TITLE
Internal Server Error 500 when creating new transaction

### ISSUE THREAD

**Issue by Petapton** [femueller/python-n26#132]
Hello, thank you for your amazing work. Wasn't expecting to find something this polished to manage a bank account...
As for the title, I'm getting error 500 when trying to initiate a transaction. It happens when using both API and CLI (on the Android app everything is ok, just to confirm I've not been banned yet).
Unfortunately HTTP server doesn't give any clues about what's going on.
```json
{
  "status": 500,
  "title": "Error",
  "message": "An unexpected error happened",
  "userMessage": {
    "title": "Error",
    "detail": "An unexpected error happened"
  }
}
```

I'm here to ask whether it happened to someone other than me and in case what was the solution.
At first I thought it was a matter of formatting the amount, but no style made it (tried integer, `%.1f` and `%.2f`; nothing worked).
Also I removed spaces from recipient's name, tried with and without BIC and reference.

Thank you in advance for any reply.

**Comment by eliaspfeffer** [comment]
Have the same error :( Did you find any solution yet? Otherwise I guess I will need to write a script to manually move around in the browser and make the transaction this way

```
PS C:\Users\USERNAME\python-n26> python -m n26 transaction
Recipient's IBAN (spaces are allowed): : (removed)
Recipient's BIC (optional): : (removed)
Recipient's name: : (removed)
Please enter your PIN (input is hidden): :
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USERNAME\python-n26\n26\__main__.py", line 4, in <module>
    cli()
  File "C:\Users\USERNAME\.virtualenvs\python-n26-TPO7hj8Z\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USERNAME\.virtualenvs\python-n26-TPO7hj8Z\Lib\site-packages\click\core.py", line 1078, in main
    rv = this.invoke(ctx)
  File "C:\Users\USERNAME\.virtualenvs\python-n26-TPO7hj8Z\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\USERNAME\.virtualenvs\python-n26-TPO7hj8Z\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(this.callback, **ctx.params)
  File "C:\Users\USERNAME\.virtualenvs\python-n26-TPO7hj8Z\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USERNAME\python-n26\n26\cli.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\USERNAME\python-n26\n26\cli.py", line 443, in transaction
    response = API_CLIENT.create_transaction(iban, bic, name, reference, amount, pin)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\python-n26\n26\api.py", line 391, in create_transaction
    return this._do_request(POST, BASE_URL_DE + '/api/transactions', json=data, headers=pin_headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\python-n26\n26\api.py", line 309, in _do_request
    response.raise_for_status()
  File "C:\Users\USERNAME\.virtualenvs\python-n26-TPO7hj8Z\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=this)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.tech26.de/api/transactions

```
