### ISSUE TITLE
Problems storing login data

### ISSUE THREAD

**Issue by SoftCreatR** [femueller/python-n26#56]
```
foo@srv4 ~ # n26 info
Traceback (most recent call last):
  File "/usr/local/bin/n26", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/n26/cli.py", line 44, in info
    account_info = API_CLIENT.get_account_info()
  File "/usr/local/lib/python3.5/dist-packages/n26/api.py", line 91, in get_account_info
    return self._do_request(GET, BASE_URL_DE + '/api/me')
  File "/usr/local/lib/python3.5/dist-packages/n26/api.py", line 265, in _do_request
    access_token = self.get_token()
  File "/usr/local/lib/python3.5/dist-packages/n26/api.py", line 291, in get_token
    token_data = self.token_data
  File "/usr/local/lib/python3.5/dist-packages/n26/api.py", line 56, in token_data
    return self._read_token_file(self.config.login_data_store_path)
  File "/usr/local/lib/python3.5/dist-packages/n26/api.py", line 75, in _read_token_file
    with open(path, "r") as file:
TypeError: invalid file: PosixPath('/home/foo/.config/n26/token_data')
```

The directory `/home/foo/.config/n26` exists and is writable. The file `token_data` has been created by me and is empty.

Without creating the file first, another error occurs:

```
foo@srv4 ~ # n26 info
Traceback (most recent call last):
  File "/usr/local/bin/n26", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/n26/cli.py", line 44, in info
    account_info = API_CLIENT.get_account_info()
  File "/usr/local/lib/python3.5/dist-packages/n26/api.py", line 91, in get_account_info
    return self._do_request(GET, BASE_URL_DE + '/api/me')
  File "/usr/local/lib/python3.5/dist-packages/n26/api.py", line 265, in _do_request
    access_token = self.get_token()
  File "/usr/local/lib/python3.5/dist-packages/n26/api.py", line 291, in get_token
    token_data = self.token_data
  File "/usr/local/lib/python3.5/dist-packages/n26/api.py", line 56, in token_data
    return self._read_token_file(self.config.login_data_store_path)
  File "/usr/local/lib/python3.5/dist-packages/n26/api.py", line 71, in _read_token_file
    path = Path(path).expanduser().resolve()
  File "/usr/lib/python3.5/pathlib.py", line 1109, in resolve
    s = self._flavour.resolve(self)
  File "/usr/lib/python3.5/pathlib.py", line 330, in resolve
    return _resolve(base, str(path)) or sep
  File "/usr/lib/python3.5/pathlib.py", line 315, in _resolve
    target = accessor.readlink(newpath)
  File "/usr/lib/python3.5/pathlib.py", line 422, in readlink
    return os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/foo/.config/n26/token_data'
```

**Comment by markusressel** [comment]
Thx for reporting, I will try to make this file access less error prone.

**Comment by markusressel** [comment]
@SoftCreatR I tested both scenarios. When you create an empty file yourself it is expected to crash since json decode will fail because it expects a json blob, but I will add a check for that.

In theory you should not have to create the directory yourself. If you have write access to any of the existing parent directories it should create them automatically. It does so on my machine which runs Manjaro linux. Can you specify more info of your environment, like what OS you are using and if there are symlinks in your path? That might cause problems since `pathlib` tries to resolve symlinks beforehand. Is it possible that you have access to the symlink but not the target folder?

**Comment by SoftCreatR** [comment]
Debian 10. The given path isn't a symlink.

**Comment by markusressel** [comment]
@SoftCreatR 
After investigating the python source and this:
https://github.com/18F/domain-scan/issues/261
I am pretty sure this is because of the python version 3.5 you seem to use. For the time being I would advise you to upgrade to python 3.6.

**Comment by SoftCreatR** [comment]
Just installed miniconda (Python 3.7) and now, it works like a charm. Thank you :)
