### ISSUE TITLE
ERR 400 : Maybe not related to package.

### ISSUE THREAD

**Issue by artenais** [femueller/python-n26#58]
I am getting kinda crazy into this one, so if any helps it will be awesome.

On curl i get : 

```
curl.exe -k -H "Authorization:Basic bXktdHJ1c3RlZC13ZHBDbGllbnQ6c2VjcmV0" -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=password&username=##MYGMAIL##&password=##MYPASS##" -X POST https://api.tech26.global/oauth/token
```

This return an error 400 - Bad credentials

N26 python returns : 
```
##UBUNTUUSER##@mydvl-01:~/.config$ python3 -m n26 balance
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/n26/__main__.py", line 4, in <module>
    cli()
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/n26/cli.py", line 95, in balance
    balance_data = API_CLIENT.get_balance()
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/n26/api.py", line 109, in get_balance
    return self._do_request(GET, BASE_URL_DE + '/api/accounts')
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/n26/api.py", line 265, in _do_request
    access_token = self.get_token()
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/n26/api.py", line 304, in get_token
    token_data = self._request_token(self.config.username, self.config.password)
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/n26/api.py", line 322, in _request_token
    mfa_token = self._initiate_authentication_flow(username, password)
  File "/home/##UBUNTUUSER##/.local/lib/python3.5/site-packages/n26/api.py", line 337, in _initiate_authentication_flow
    raise ValueError("Unexpected response for initial auth request: {}".format(response.text))
ValueError: Unexpected response for initial auth request: {"status":400,"detail":"Bad credentials","type":"invalid_grant","userMessage":{"title":"Loginddress or password is incorrect"},"error":"invalid_grant","error_description":"Bad credentials"}
```

So i wrapped into node.js and behold, I got a totally different error : 

```
async function n26token ( usr, pwd ) {
    var tokendata = {
        'grant_type' : 'password',
        username :  usr,
        password : pwd, 
    }
    var uri = "https://api.tech26.global/oauth/token"
    var tokendata = JSON.stringify(tokendata)
    return await new Promise ((resolve, reject ) => request({ 
            headers: {
                Host: 'api.tech26.global',
                Authorization: 'Basic bXktdHJ1c3RlZC13ZHBDbGllbnQ6c2VjcmV0',
                "Content-Type" : 'application/x-www-form-urlencoded',
                Accept: '*/*',
                'Accept-Encoding' : 'gzip, deflate',
                'Content-Length' : tokendata.length,
                Connection: 'keep-alive',
                'cache-control' : 'no-cache'
            },
            uri: uri ,
            method: 'POST',
            data : tokendata
      }, async function (err, res, body){
        if ( err ) {
            console.log(err)
        } else {
            //console.log(res)
            console.log(body)
        }
    }))
//CLOSE ASYNC
}
```
```
{"status":401,"detail":"Unauthorized grant type: client_credentials","type":"invalid_client","userMessage":{"title":"error.oauth2.invalid_client.title","detail":"error.oauth2.invalid_client.detail"},"error":"invalid_client","error_description":"Unauthorized grant type: client_credentials"}
```

Now things get interesting. Let's drop a call into PostMan, same config : 
```
{
    "userMessage": {
        "title": "A second authentication factor is required.",
        "detail": "Please provide your second form of authentication."
    },
    "mfaToken": "##BLAHBLA##",
    "error_description": "MFA token is required",
    "detail": "MFA token is required",
    "hostUrl": "https://api.tech26.de",
    "type": "mfa_required",
    "error": "mfa_required",
    "title": "A second authentication factor is required.",
    "message": "Please provide your second form of authentication.",
    "userId": "##BLAHBLA##",
    "status": 403
}
```

I am a litte confused? Any idea?

**Comment by markusressel** [comment]
Are you 100% sure you didn't mess up your credentials by accident? Maybe some character encoding/escaping gone wrong? This might happen on our side as well.

The node.js test indicates that the user-agent might indeed be necessary. I omitted this detail because it was working for me without the user agent but maybe we should include it anyway.

**Comment by artenais** [comment]
Hi, 

I do not know if this may help you but it seems the following node code works.

    return await new Promise ((resolve, reject ) => request({ 
            headers: {

                'Authorization': 'Basic bXktdHJ1c3RlZC13ZHBDbGllbnQ6c2VjcmV0',
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            uri: uri ,
            method: 'POST',
            **form: { 
                grant_type: 'password',
                username: usr,
                password: pwd 
            }**
      }, function (err, res, body){
        if ( err ) {
            console.log(err)
        } else {
            console.log(res)
            console.log(body)
            console.log(uri)
        }
    //CLOSE N26 EVENT
    }))

It seems the data should be passed as a form and not as body. I do not know if any of your user is affected from this and I hope this will help you.

**Comment by markusressel** [comment]
So... is this issue resolved then?
Did you check your credentials again? Because if the server responds with a "Bad credentials" I'm pretty sure the credentials are wrong :smile:

**Comment by artenais** [comment]
Good Morning ( well... at least here ). Nope the issue is not resolved, since it works only on my node mockup. I suppose has something do to with encoding the character  

.

In the password. I will close this, but leave it for future reference if you need.
