### ISSUE TITLE
Unexpected Keyword

### ISSUE THREAD

**Issue by azlux** [femueller/python-n26#72]
Hi,
I just try you script. And I have this error at first n26 call.

```
root@weboob:~/.config$ /usr/local/bin/n26 -json balance
Traceback (most recent call last):
  File "/usr/local/bin/n26", line 6, in <module>
    from n26.cli import cli
  File "/usr/local/lib/python3.7/dist-packages/n26/cli.py", line 16, in <module>
    API_CLIENT = api.Api()
  File "/usr/local/lib/python3.7/dist-packages/n26/api.py", line 48, in __init__
    cfg = Config(write_reference=False)
  File "/usr/local/lib/python3.7/dist-packages/n26/config.py", line 30, in __new__
    return super(Config, cls).__new__(cls, *args, **kwargs)
TypeError: __new__() got an unexpected keyword argument 'write_reference'
```

Any idea what's append here ?

Best regards
Azlux

**Comment by markusressel** [comment]
There was a breaking change in [container-app-conf](https://github.com/markusressel/container-app-conf) which we use for config parsing. I guess our pipenv definition isn't strict enough so you got version `5.0.0` installed although n26 is only compatible with `4.2.3`. I will fix this asap.
